services:
  web: # ← コンテナに"web"という名前をつける
    build:
      context: .
      dockerfile: Dockerfile.dev # ← Dockerfile.devを使ってビルドする、という指示
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
             bundle exec rails db:migrate &&
             tail -f /dev/null"
    volumes: # ← どのフォルダを同期するか
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports: # ← どのポートを外に公開するか
      - "3000:3000"
    environment:
      - RAILS_ENV=development

volumes:
  bundle_cache:
